# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-29 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=1024, null=True)),
                ('existeFogo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Avalia\xe7\xe3o',
                'verbose_name_plural': 'Avalia\xe7\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=1024, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
            },
        ),
        migrations.CreateModel(
            name='Foco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('satelite', models.CharField(max_length=255)),
                ('data_hora_gmt', models.DateTimeField()),
                ('tipo', models.CharField(default='Oficial', max_length=256)),
            ],
            options={
                'verbose_name': 'Foco de incendio',
                'verbose_name_plural': 'Focos de incendios',
            },
        ),
        migrations.CreateModel(
            name='FotoAvaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caminho', models.CharField(blank=True, max_length=1024, null=True)),
                ('legenda', models.CharField(blank=True, max_length=1024, null=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fotos', to='core.Avaliacao')),
            ],
            options={
                'verbose_name': 'Foto de Avalia\xe7\xe3o',
                'verbose_name_plural': 'Fotos de Avalia\xe7\xf5es',
            },
        ),
        migrations.CreateModel(
            name='FotoDenuncia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caminho', models.CharField(blank=True, max_length=1024, null=True)),
                ('legenda', models.CharField(blank=True, max_length=1024, null=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fotos', to='core.Denuncia')),
            ],
            options={
                'verbose_name': 'Foto de Denuncia',
                'verbose_name_plural': 'Fotos de Denuncias',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=512)),
                ('senha', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Usu\xe1rio',
                'verbose_name_plural': 'Usu\xe1rios',
            },
        ),
        migrations.AddField(
            model_name='denuncia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Denuncias', to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='foco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Avaliacoes', to='core.Foco'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Avaliacoes', to='core.Usuario'),
        ),
    ]
